<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/user.proto

namespace Mszlu\Pb\User;

/**
 * Protobuf type <code>user.UserService</code>
 */
interface UserServiceInterface
{
    /**
     *rpc 服务的函数名 （传入参数）返回（返回参数）
     *
     * Method <code>search</code>
     *
     * @param \Mszlu\Pb\User\UserRequest $request
     * @return \Mszlu\Pb\User\UserResponse
     */
    public function search(\Mszlu\Pb\User\UserRequest $request);

}

